### ISSUE TITLE
Unable to start a tunnel (2.2.8)

### ISSUE THREAD

**Issue by thekevinscott** [robbie-cahill/tunnelmole-client#29]
I'm seeing the following error on `2.2.8` when starting a tunnel:

```
1700274107834Caught an error:
AggregateError:
    at internalConnectMultiple (node:net:1114:18)
    at afterConnectMultiple (node:net:1667:5) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED ::1:8081
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8081
    },
    Error: connect ECONNREFUSED 127.0.0.1:8081
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 8081
    }
  ]
}
```

The local server is reachable at `localhost:<port>`.

**Comment by thekevinscott** [comment]
The above was from Node. Just tried from the command line:

> pnpm tmole 3000

                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
          ^
FetchError: request to http://localhost:8001/tunnelmole-log-telemetry failed, reason:
    at ClientRequest.<anonymous> (/path/to/local/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Dario-Pacule** [comment]
I also have the same problem

**Comment by tbm206** [comment]
I'm also seeing this now

```
FetchError: request to http://localhost:8001/tunnelmole-log-telemetry failed, reason: 
    at ClientRequest.<anonymous> (/home/h/.nvm/versions/node/v20.9.0/lib/node_modules/tunnelmole/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by thekevinscott** [comment]
I've run through the old versions to test, from `2.2.8` back to `2.1.0` (the `2.0.x` versions have ~0 downloads so I stopped there).

I'm testing by using `pnpm dlx` (akin to `npx`), not sure if there's anything related to post install that would corrupt these results:

```
pnpm --package=tunnelmole@2.1.8 dlx tmole 3000
pnpm --package=tunnelmole@2.2.7 dlx tmole 3000
pnpm --package=tunnelmole@2.2.6 dlx tmole 3000
pnpm --package=tunnelmole@2.2.5 dlx tmole 3000
pnpm --package=tunnelmole@2.2.4 dlx tmole 3000
pnpm --package=tunnelmole@2.2.3 dlx tmole 3000
pnpm --package=tunnelmole@2.2.2 dlx tmole 3000
pnpm --package=tunnelmole@2.2.1 dlx tmole 3000
pnpm --package=tunnelmole@2.2.0 dlx tmole 3000
pnpm --package=tunnelmole@2.1.12 dlx tmole 3000
pnpm --package=tunnelmole@2.1.11 dlx tmole 3000
pnpm --package=tunnelmole@2.1.10 dlx tmole 3000
pnpm --package=tunnelmole@2.1.9 dlx tmole 3000
pnpm --package=tunnelmole@2.1.8 dlx tmole 3000
pnpm --package=tunnelmole@2.1.7 dlx tmole 3000
pnpm --package=tunnelmole@2.1.6 dlx tmole 3000
pnpm --package=tunnelmole@2.1.5 dlx tmole 3000
pnpm --package=tunnelmole@2.1.4 dlx tmole 3000
pnpm --package=tunnelmole@2.1.3 dlx tmole 3000
pnpm --package=tunnelmole@2.1.2 dlx tmole 3000
pnpm --package=tunnelmole@2.1.1 dlx tmole 3000
pnpm --package=tunnelmole@2.1.0 dlx tmole 3000
```

`2.2.7` in particular fails with the request above:

```
/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53984/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501
                        reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
          ^
FetchError: request to http://localhost:8001/tunnelmole-log-telemetry failed, reason:
    at ClientRequest.<anonymous> (/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53984/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```


All the others fail with the following:

```
TypeError: handler is not a function
    at HostipWebSocket.<anonymous> (file:///Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53971/node_modules/.pnpm/tunnelmole@2.1.8/node_modules/tunnelmole/src/tunnelmole.ts:84:9)
    at HostipWebSocket.emit (node:events:526:35)
    at Receiver.receiverOnMessage (/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53971/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/websocket.js:1068:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53971/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData (/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53971/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/receiver.js:435:17)
    at Receiver.startLoop (/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53971/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/Users/thekevinscott/Library/pnpm/store/v3/tmp/dlx-53971/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:447:12)
    at _write (node:internal/streams/writable:389:10)
```

Again, not sure if there's something specific to `pnpm dlx` that would corrupt these results but sharing if it's helpful.

**Comment by robbie-cahill** [comment]
> I'm seeing the following error on `2.2.8` when starting a tunnel:
> 
> ```
> 1700274107834Caught an error:
> AggregateError:
>     at internalConnectMultiple (node:net:1114:18)
>     at afterConnectMultiple (node:net:1667:5) {
>   code: 'ECONNREFUSED',
>   [errors]: [
>     Error: connect ECONNREFUSED ::1:8081
>         at createConnectionError (node:net:1634:14)
>         at afterConnectMultiple (node:net:1664:40) {
>       errno: -61,
>       code: 'ECONNREFUSED',
>       syscall: 'connect',
>       address: '::1',
>       port: 8081
>     },
>     Error: connect ECONNREFUSED 127.0.0.1:8081
>         at createConnectionError (node:net:1634:14)
>         at afterConnectMultiple (node:net:1664:40) {
>       errno: -61,
>       code: 'ECONNREFUSED',
>       syscall: 'connect',
>       address: '127.0.0.1',
>       port: 8081
>     }
>   ]
> }
> ```
> 
> The local server is reachable at `localhost:<port>`.

Just on this error, I am assuming you've cloned the repo and are starting Tunnelmole with `dist/bin/tunnelmole.js`? It looks like its trying to connect to a locally running https://github.com/robbie-cahill/tunnelmole-service. You'll need to update the endpoint to production unless you want to use your own server.

Update config-instance.toml to
```
const instanceConfig = {
    hostip: {
        endpoint: "wss://service.tunnelmole.com:8083",
        httpEndpoint: "https://service.tunnelmole.com"
    },
    runtime: {
        enableLogging: true
    }
}
```

**Comment by robbie-cahill** [comment]
Actually looks like it is the `npm` version. I think I inadvertently had it configured to use local when I published it. I've published a new version, `2.2.9` to fix that. Could you update to this version and try again?

**Comment by rowaxl** [comment]
Hi
I updated it to `2.2.9` and it stop showing above errors. But it shows `You have hit the limit for the number of custom subdomains~` error now.
(It shows empty current domains, which means unable to `--unreserve-subdomain <subdomain>` )
Any help?

**Comment by robbie-cahill** [comment]
It seems this impacts brand new installs, looks like I missed that test case. I just deployed a fix to production, can you try again?

**Comment by abbyck** [comment]
@robbie-cahill It works perfectly now 🎉 Thank you for the quick fix

**Comment by thekevinscott** [comment]
It's working for me as well (on `2.2.9`). Thank you @robbie-cahill for the quick fix!

**Comment by emonxcode** [comment]
not working
