### ISSUE TITLE
Cant npm install on widnows 10

### ISSUE THREAD

**Issue by ach-raf** [robbie-cahill/tunnelmole-client#50]
Node Version: v20.9.0
OS: Windows 10
I'm sure node and npm works, other projects work.
I already tried running as administrator, clearing the npm cache, manually removing the node_modules folder.

PS D:\programming\tunnelmole-client> npm install
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     'D:\\programming\\tunnelmole-client\\node_modules\\validator',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\programming\tunnelmole-client\node_modules\validator\es'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'D:\\programming\\tunnelmole-client\\node_modules\\validator\\es'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path D:\programming\tunnelmole-client\node_modules\tunnelmole
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c cjs/bin/postinstall.js
npm error 'cjs' is not recognized as an internal or external command,
npm error operable program or batch file.
npm error A complete log of this run can be found in: \_logs\2024-06-11T23_58_21_889Z-debug-0.log

warn cleanup Failed to remove some directories [
41 warn cleanup   [
41 warn cleanup     'D:\\programming\\tunnelmole-client\\node_modules',
41 warn cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\programming\tunnelmole-client\node_modules\bl'] {
41 warn cleanup       errno: -4048,
41 warn cleanup       code: 'EPERM',
41 warn cleanup       syscall: 'rmdir',
41 warn cleanup       path: 'D:\\programming\\tunnelmole-client\\node_modules\\bl'
41 warn cleanup     }
41 warn cleanup   ]
41 warn cleanup ]
42 verbose stack Error: command failed
42 verbose stack     at promiseSpawn (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
42 verbose stack     at spawnWithShell (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
42 verbose stack     at promiseSpawn (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
42 verbose stack     at runScriptPkg (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
42 verbose stack     at runScript (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:9:12)
42 verbose stack     at C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\rebuild.js:329:17
42 verbose stack     at run (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:67:22)
42 verbose stack     at C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:84:9
42 verbose stack     at new Promise (<anonymous>)
42 verbose stack     at callLimit (C:\Users\USER\AppData\Roaming\npm\node_modules\npm\node_modules\promise-call-limit\dist\commonjs\index.js:35:69)
43 verbose pkgid tunnelmole@2.1.5
44 error code 1
45 error path D:\programming\tunnelmole-client\node_modules\tunnelmole
46 error command failed
47 error command C:\Windows\system32\cmd.exe /d /s /c cjs/bin/postinstall.js
48 error 'cjs' is not recognized as an internal or external command,
48 error operable program or batch file.
49 silly unfinished npm timer reify 1718150553350
50 silly unfinished npm timer reify:build 1718150611345
51 silly unfinished npm timer build 1718150611346
52 silly unfinished npm timer build:deps 1718150611347
53 silly unfinished npm timer build:run:postinstall 1718150611395
54 silly unfinished npm timer build:run:postinstall:node_modules/tunnelmole 1718150611396
55 verbose cwd D:\programming\tunnelmole-client
56 verbose os Windows_NT 10.0.19044
57 verbose node v20.9.0
58 verbose npm  v10.8.1
59 verbose exit 1
60 verbose code 1

**Comment by robbie-cahill** [comment]
I'm not a windows user and  do not have a windows install available to test with, but I think I can see some permissions errors in your logs.

You should try fixing those first. If you find a solution let me know.

**Comment by lonasozo** [comment]
Don't know if it can be usefule, I've Win 11, but using WSL
`curl -O https://install.tunnelmole.com/xD345/install && sudo bash install
`
it works pretty fine. If have it through NPM is not mandatory I suggest you to try it! 

P.s. additionally from your logs, I think it could be useful to check the _logs\2024-06-11T23_58_21_889Z-debug-0.log output to debug it
